name: Deploy PhonebookApp #워크플로워 이름 

#on: 
#  workflow_dispatch:

on:  #이벤트 정의
  push:  #2칸
     branches: #4칸 
      - master # 6칸 master 깃허브에 push가 되면 작동 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build . -t sunkisttttttt/phonebook:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push sunkisttttttt/phonebook:latest
        
  SSH:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ssh to ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull sunkisttttttt/phonebook:latest
            sudo docker stop phonebook || true
            sudo docker rm phonebook || true
            sudo docker run -d --name phonebook -p 9002:9002 sunkisttttttt/phonebook:latest